version: '3.8'

services:
  webapp:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
    command: npm run dev                              # for development
    # command: sh -c "npm run build && npm run start" # for production

volumes:
  node_modules:
